import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../../styles/Home.module.css";
import dynamic from "next/dynamic";
import styled from "styled-components";

const MainPageCenterCanvas = dynamic(
  () => import("../components/mainPageCenterCanvas")
);
// color3 색상
//https://forum.babylonjs.com/t/simple-tool-to-convert-hexadecimal-colors-to-babylon-color-code/286
const Home: NextPage = () => {
  return (
    <>
      <HomeMainNav className="zindex1">
        <NavInner>
          <NavItem className="hover">Info</NavItem>
          <NavItem className="hover">Hello</NavItem>
          <NavItem className="hover">Hi</NavItem>
          <NavItem className="hover">How</NavItem>
          <NavItem className="hover">Are</NavItem>
          <NavItem className="hover">You?</NavItem>
          <NavItemMenu></NavItemMenu>
          <NavItemMenu></NavItemMenu>
          <NavItemMenu></NavItemMenu>
          <NavItemMenu></NavItemMenu>
          <NavItemMenu></NavItemMenu>
          <NavItemMenu>Menu</NavItemMenu>
        </NavInner>
      </HomeMainNav>
      <HomeMainContainer>
        <Head>
          <title>PocketGarden</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <HomeMainSectionOne>
          <SectionOneItemDiv>
            <h2 className="zindex1">Lorem ipsum dolor sit amet</h2>
            <h1 className="zindex1">consectetur adipiscing elit.</h1>
          </SectionOneItemDiv>
          <SectionOneItemDiv>
            <MainPageCenterCanvas />
            <BlankCanvasCopy />
          </SectionOneItemDiv>
          <SectionOneItemDiv>
            <h2 className="zindex1">Sed feugiat quam vitae diam iaculis imperdiet.</h2>
            <h1 className="zindex1">Nullam risus nunc, congue nec mattis vitae, malesuada nec elit.</h1>
          </SectionOneItemDiv>
        </HomeMainSectionOne>
        <StartBtnWrapper className="zindex1">
          <StartBtn className="hover">시작하기</StartBtn>
        </StartBtnWrapper>
      </HomeMainContainer>
    </>
  );

  {
    /* <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */
  }
};

export default Home;

const HomeMainContainer = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  padding-left: 5%;
  padding-right: 5%;
`;

const HomeMainSectionOne = styled.section`
  display: flex;

  @media screen and (max-width: 970px) {
    flex-direction: column;
    /* justify-content: center; */
    margin-top: 50px;
  }
`;

const BlankCanvasCopy = styled.canvas`
  width: 100%;
  height: 90vh;

`;

const HomeMainNav = styled.nav`
  position: absolute;
  width: 100%;
  height: 10vh;
  background-color: rgba(255, 255, 255, 0);
  /* background: rgb(45,43,92);
background: linear-gradient(77deg, rgba(45,43,92,1) 0%, rgba(95,95,150,1) 49%, rgba(221,221,255,1) 100%, rgba(0,212,255,1) 100%); */
`;

const NavInner = styled.ul`
  display: flex;
  list-style: none;
  justify-content: space-around;
  @media screen and (max-width: 970px) {
    justify-content: space-between;
  }
`;

const NavItem = styled.li`
@media screen and (max-width: 970px) {
    display:none;
  }
`;
const NavItemMenu = styled.div`
  background-color:red;
  margin-right:20px;
  @media screen and (min-width: 970px) {
    display:none;
  }
`

const HomeMainSectionTwo = styled.section``;
const HomeMainSectionThree = styled.section``;

const SectionOneItemDiv = styled.div`
  display: flex;
  flex-direction: column;
  justify-content: center;
  text-align: center;
`;
const SectionTwoItemDiv = styled.div``;

const StartBtnWrapper = styled.div`
  display: flex;
  position:absolute;
  justify-content: center;
  top:92%;
  width: 90vw;
  height: 40px;
`;
const StartBtn = styled.div`
  width: 260px;
  height: 30px;
  border: 1px solid purple;
  text-align: center;
  padding-top:5px;
  border-radius: 7px;
  background-image: linear-gradient(to top, #cfd9df 0%, #e2ebf0 100%);
  opacity: 0.8;
`;
